# Module: system
# Docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-system.html

- module: system
  # Syslog
  syslog:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/hostfs/var/log/messages*", "/hostfs/var/log/syslog*"]

  # Authorization logs
  auth:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/hostfs/var/log/auth.log*", "/hostfs/var/log/secure*"]