services:

  enterprise-search:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/enterprise-search/enterprise-search:${ELASTIC_STACK_VERSION}
    container_name: enterprise-search
    restart: on-failure
    volumes:
      - type: bind
        source: ./extensions/enterprise-search/config/enterprise-search.yml
        target: /usr/share/enterprise-search/config/enterprise-search.yml
        read_only: true
      - type: volume
        source: certs
        target: /usr/share/enterprise-search/config/certs
        read_only: true
    ports:
      - ${ENT_SEARCH_PORT}:3002
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    mem_limit: ${ENT_SEARCH_MEM_LIMIT}
    networks:
      - default
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:3002 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120