apm-server:
  host: 0.0.0.0:8200

tags: [ "docker-elk" ]
fields:
  env: "dev"
fields_under_root: true

processors:
- add_host_metadata: ~
- add_docker_metadata: ~
- decode_json_fields:
    fields: ["message"]
    process_array: false
    max_depth: 1
    target: ""
    overwrite_keys: true

output:
  elasticsearch:
    hosts: ['http://elasticsearch:9200']
    username: elastic
    password: changeme

setup.template:
  overwrite: true
  settings.index:
    number_of_shards: 1
    number_of_replicas: 0

# Only if direct output to elasticsearch. Won't be used if logstash output. 
# setup.ilm:
#   enabled: auto
#   rollover_alias: "apm" # should be set with basic licence
#   pattern: "-000001" # should be set with basic licence
#   overwrite: true

setup.kibana:
  host: "kibana:5601"
  protocol: "http"
  username: "elastic"
  password: "changeme"
  space.id: ""

logging.level: warning
logging.json: true
logging.metrics.enabled: false
logging.ecs: false