---
######################## Metricbeat Configuration ##########################

# This file is aan extract of the full configuration example documenting 
# all non-deprecated options in comments. 
# For the full configuration example: 
# https://github.com/elastic/beats/blob/main/metricbeat/metricbeat.reference.yml
# For a shorter configuration example, that contains only the most common options: 
# https://github.com/elastic/beats/blob/main/metricbeat/metricbeat.yml
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/current/index.html

#============================== Autodiscover ===================================

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#============================  Config Reloading ===============================
# Config reloading allows to dynamically load modules. Each file which is
# monitored must contain one or multiple modules as a list.

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 10s



# ================================== General ===================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.

name: Zenika
timestamp.precision: microsecond
tags: [ "docker-elk" ]
fields:
  env: "dev"
#fields_under_root: true

# ================================= Processors =================================
# Processors are used to reduce the number of fields in the exported event or to
# enhance the event with external metadata.

processors:
  - add_host_metadata: ~
#  - add_docker_metadata: ~
  - add_locale:
      format: ~

# ================================== Outputs ===================================
# Configure what output to use when sending the data collected by the beat.

# ---------------------------- Elasticsearch Output ----------------------------

# output.elasticsearch:
#   hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
#   username: elastic
#   password: changeme
#   ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
#   loadbalance: true
#   worker: 2

# ------------------------------ Logstash Output -------------------------------

output.logstash:
  hosts: ["logstash:5044"]

# ================================= Dashboards =================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards are disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag or the `setup` command.  

setup.dashboards:
  enable: true
  #index: ?

# ================================== Template ==================================
# A template is used to set the mapping in Elasticsearch
# By default template loading is enabled and the template is loaded.
# These settings can be adjusted to load your own template or overwrite existing ones.

setup.template:
  enable: true
  overwrite: true
  #name: "filebeat-%{[agent.version]}"
  #pattern: "filebeat-%{[agent.version]}"
  #json:
    #path: "${path.config}/template.json"
    #name: ""
    #data_stream: true
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 0
      #mapping.total_fields.limit: 10000

# ====================== Index Lifecycle Management (ILM) ======================
# Configure index lifecycle management (ILM) to manage the backing indices
# of your data streams.

setup.ilm:
  enabled: true
  policy_name: "metricbeat" 
  #policy_file: /path
  check_exists: true
  overwrite: false
  
# =================================== Kibana ===================================
# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.

setup.kibana:
  host: "kibana:5601"
  protocol: "http"
  username: "elastic"
  password: "changeme"
  space.id: ""

# ================================== Logging ===================================
# There are four options for the log output: file, stderr, syslog, eventlog
# The file output is the default.

logging:
  level: info
  json: true
  metrics:
    enabled: false
    #period: 30s

# ============================= X-Pack Monitoring ==============================
# Filebeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

monitoring.enabled: false

# =============================== HTTP Endpoint ================================
# Each beat can expose internal metrics through a HTTP endpoint. For security
# reasons the endpoint is disabled by default. This feature is currently experimental.
# Stats can be access through http://localhost:5066/stats . For pretty JSON output
# append ?pretty to the URL.

http.enabled: true
http.host: 0.0.0.0
http.port: 5066

system.hostfs: /hostfs