services:

  fleet-server:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/beats/elastic-agent:${ELASTIC_STACK_VERSION}
    container_name: fleet-server
    user: elastic-agent
    restart: on-failure
    volumes:
      - type: bind
        source: ./extensions/fleet-server/config/elastic-agent.yml
        target: /usr/share/elastic-agent/elastic-agent.yml
        read_only: true
      - type: volume
        source: certs
        target: /usr/share/elastic-agent/certs
        read_only: true
    ports:
      - ${FLEET_SERVER_PORT}:8220
    environment:
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD} 
      - FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca/ca.crt
      - FLEET_SERVER_POLICY_ID=fleet_server_policy
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/certs/fleet-server/fleet-server.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/certs/fleet-server/fleet-server.key
      - FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt
      - FLEET_URL=https://fleet-server:${FLEET_SERVER_PORT}
      - FLEET_ENROLL=1
    mem_limit: ${FLEET_SERVER_MEM_LIMIT}
    networks:
      - default
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert certs/ca/ca.crt -X GET https://localhost:8220/api/status | grep -c 'HEALTHY'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120