# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
  username: remote_monitoring_user
  password: ${REMOTE_MONITORING_USER_PASSWORD}
  ssl.certificate_authorities: "/usr/share/metricbeat/certs/ca/ca.crt"