---
server.host: "0.0.0.0"
server.name: "kibana"

elasticsearch.username: "kibana_system"
elasticsearch.ssl.certificateAuthorities: [ "config/certs/ca/ca.crt" ]

xpack.encryptedSavedObjects.encryptionKey: dc3bfa3b97a605d4b07a4fbddfd63029
xpack.reporting.encryptionKey: 3072aa993391749a7cfd4db97f9df7ca
xpack.security.encryptionKey: cccb93bfad885f795824230543c6bd6c

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

logging.appenders.default:
  type: console
  layout: 
    type: json