# Module: openmetrics
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-openmetrics.html

- module: openmetrics
  period: 10s
  metricsets: ["collector"]
  hosts: ["host.docker.internal:8080"]
  metrics_path: /metrics
  metrics_filters:
    include: ["myapp*"]