# Module: prometheus
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html

- module: prometheus
  period: 10s
  hosts: ["prometheus:9090"]
  metrics_path: /metrics

- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["host.docker.internal:9091"]
  metrics_path: /metrics
  metrics_filters:
    include: ["myapp*"]