input {
  	file {
    	id => "prizes"
		path => "/usr/share/logstash/pipeline/file/prizes.json"
		mode => "read"
		codec => "json"
		start_position => "beginning"
		sincedb_path => "/dev/null"
  	}
}

filter {
	json {
		source => message
		remove_field => message
	}
	mutate {
		remove_field => ["@timestamp", "@version", "event", "host", "log"]
	}
}

filter {
	ruby {
        id => "denormalized-by-prizes"
        path => "/usr/share/logstash/pipeline/file/denormalized_by_prizes_using_module.rb"
        script_params => {
			"keep_original_event" => true
        }
	}
	mutate {
		remove_field => ["@timestamp", "@version", "event", "host", "log"]
        
	}
	if "male" not in [gender] and "female" not in [gender]
    {
      mutate 
      { 
          add_tag => ["if male not in gender and female not in gender"]
      }
    }
	#if ["male", "female"] not in [gender]
    #{
    #  mutate 
    #  { 
    #      add_tag => ["if male, female not in gender"]
    #  }
    #}
	if [gender] not in ["male", "female"] 
    {
      mutate 
      { 
          add_tag => ["if gender not in male, female"]
      }
    }
}

#output {
#	stdout {
#		codec => rubydebug { metadata => true }
#	}
#}

output {
	elasticsearch {
		index => "%{[@metadata][_index]}"
		hosts => ["https://es01:9200","https://es02:9200","https://es03:9200"]
		ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
		user => "elastic"
		password => "${ELASTIC_PASSWORD}"
	}
}
