heartbeat.monitors:
- type: http
  name: Synthetics demo
  id: synthetics-demo
  enabled: true
  urls: "https://elastic.github.io/synthetics-demo/"
  schedule: '@every 1m'
  timeout: 20s
  alert.status.enabled: true
