---
## Enterprise Search core configuration
## https://www.elastic.co/guide/en/enterprise-search/current/configuration.html
#

## --------------------- Secrets ---------------------

# Encryption keys to protect application secrets.
secret_management.encryption_keys: 
  - obhbrkzitz4qdva4etewxjopy0abph5mguykd30vmqe2w73imsokvs9z1j1vaery

## --------------------- Elasticsearch ---------------------

# Allow Enterprise Search to modify Elasticsearch settings. Used to enable auto-creation of Elasticsearch indexes.
allow_es_settings_modification: true

# Elasticsearch URL and credentials
elasticsearch.host: https://es01:9200
elasticsearch.username: elastic
elasticsearch.password: ${ELASTIC_PASSWORD}
elasticsearch.ssl.enabled: true
elasticsearch.ssl.certificate_authority: "/usr/share/enterprise-search/config/certs/ca/ca.crt"
elasticsearch.ssl.verify: false

## --------------------- Kibana ---------------------

# URL at which Enterprise Search can reach Kibana. 
kibana.host: http://kibana:5601

# Exposed URL at which users can reach Kibana. 
kibana.external_url: http://localhost:5601

## --------------------- Hosting and network ---------------------

# URL at which users reach Enterprise Search / Kibana
ent_search.external_url: http://localhost:3002

# IP address Enterprise Search listens on
ent_search.listen_host: 0.0.0.0

## --------------------- Logging ---------------------

# Log level can be: debug, info, warn, error, fatal, or unknown.
log_level: info



